language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator9.0
script: "xcodebuild test -project Heimdall.xcodeproj -scheme Heimdall -destination \"platform=iOS Simulator,name=iPhone 6,OS=9.3\""
